# GEC Prompt Engineering Experiment

## Goal
Generate realistic grammatically-erroneous sentences via LLM (Qwen-3 on OpenRouter),
correct them with T5-base-grammar-correction, and evaluate with three complementary metrics.

## Pipeline
```
C4_200M sample (A)  →  LLM generates new erroneous sentences (B)
                    →  T5 corrects B → C
                    →  Eval: CoLA(B) < CoLA(A),  CoLA(C) > CoLA(B),  ERRANT F0.5
```

## Plan steps
1. **Error scope** — 12 ERRANT categories (`gec_error_types.json`)
2. **Zero-shot baseline** — instruction only, no examples
3. **Few-shot stratified** — 3-shot (balanced) and 12-shot (full coverage)
4. **Chain-of-Thought** — explicit error-type identification before generation
5. **Systematic ablation** — one variable at a time → ERRANT F0.5 leaderboard

In [1]:
import os, json, time, re, glob, warnings
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

warnings.filterwarnings('ignore')

# The Jupyter kernel CWD is the workspace root (/workspaces/live-eval),
# not the Denis/ subfolder where .env lives. Try both.
load_dotenv()  # works if kernel CWD == Denis/
if not os.getenv('OPENROUTER_API_KEY'):
    load_dotenv('Denis/.env')  # works if kernel CWD == workspace root

assert os.getenv('OPENROUTER_API_KEY'), 'OPENROUTER_API_KEY not found — check Denis/.env'
print('Imports OK — API key loaded')

/opt/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Imports OK — API key loaded

In [2]:
# qwen-3.6 Plus (free tier) via OpenRouter
# Free Qwen models available as of 2026-04: qwen/qwen3-next-80b-a3b-instruct:free
# Fallback if unavailable: 'nvidia/nemotron-3-super-120b-a12b:free'
LLM_MODEL = 'nvidia/nemotron-3-super-120b-a12b:free'

def make_llm(temperature=0.7):
    return ChatOpenAI(
        model=LLM_MODEL,
        api_key=os.getenv('OPENROUTER_API_KEY'),
        base_url='https://openrouter.ai/api/v1',
        temperature=temperature,
    )

llm = make_llm()
print(f'LLM ready: {LLM_MODEL}')

LLM ready: nvidia/nemotron-3-super-120b-a12b:free

In [3]:
with open('gec_error_types.json') as f:
    error_types = json.load(f)['error_types']

with open('gec_few_shot_examples.json') as f:
    few_shot_data = json.load(f)

demonstrations = few_shot_data['demonstrations']   # 12 (input, output) pairs, one per error type
few_shot_examples = few_shot_data['few_shot_examples']  # 3 examples per type for ablation

print(f'Loaded {len(error_types)} error types:')
for et in error_types:
    print(f'  {et["name"]}: "{et["example"]}"')

Loaded 12 error types:
  subject_verb_agreement: "The group of students are going to the library."
  article: "She adopted a old cat from the shelter."
  preposition: "He is good in playing the guitar."
  verb_tense: "Yesterday, she goes to the market and buys vegetables."
  spelling: "The goverment announced new education policies."
  verb_form: "He has went to the store three times this week."
  noun_number: "She gave me a lot of advices about the project."
  pronoun: "Everyone should bring their own lunch, but him forgot."
  word_order: "She always is late to the morning meetings."
  punctuation: "However she decided to stay and finish the report."
  conjunction: "He studied hard, but however he failed the exam."
  adjective: "This is the most cheapest option available in the store."

## Step 1 — Error Scope

All 12 ERRANT categories we target. Using the full set ensures broad benchmark coverage
and avoids bias toward frequent types (SVA, articles dominate C4).

For ablation we also test **balanced-3** (SVA, article, verb_tense) vs **full-12** few-shot coverage
to measure whether more examples always help.

In [4]:
err_df = pd.DataFrame(error_types).rename(columns={'name': 'error_type', 'example': 'example_sentence'})
err_df.index = range(1, len(err_df) + 1)
err_df

                error_type                                   example_sentence
1   subject_verb_agreement    The group of students are going to the library.
2                  article            She adopted a old cat from the shelter.
3              preposition                  He is good in playing the guitar.
4               verb_tense  Yesterday, she goes to the market and buys veg...
5                 spelling    The goverment announced new education policies.
6                verb_form    He has went to the store three times this week.
7              noun_number    She gave me a lot of advices about the project.
8                  pronoun  Everyone should bring their own lunch, but him...
9               word_order        She always is late to the morning meetings.
10             punctuation  However she decided to stay and finish the rep...
11             conjunction   He studied hard, but however he failed the exam.
12               adjective  This is the most cheapest option available in ...

## Step 2 — Data Sampling

`C4_200M` is split across 10 TSV files. To avoid RAM overflow we read each file in
`chunksize=5000` chunks, reservoir-sample `n_rows` per chunk, then downsample to exactly
`n_rows` per file. Peak RAM is bounded by `~chunksize × 2` rows regardless of file size.

| Mode | Per file | Total |
|------|----------|-------|
| Demo | 10 | 100 |
| Full | 100 | 1 000 |

In [5]:
def sample_from_tsv(pattern, n_rows, seed=42, chunksize=5000):
    """Memory-safe sampling from TSV files matching a glob pattern."""
    files = sorted(glob.glob(pattern))
    if not files:
        raise FileNotFoundError(f'No files matched: {pattern}')

    chunks = []
    for path in tqdm(files, desc='Sampling files'):
        reservoir = []
        for chunk in pd.read_csv(
            path, sep='\t', header=None,
            names=['original', 'ground_truth'],
            chunksize=chunksize
        ):
            n = min(n_rows, len(chunk))
            reservoir.append(chunk.sample(n=n, random_state=seed))
        file_sample = pd.concat(reservoir).sample(n=n_rows, random_state=seed).reset_index(drop=True)
        chunks.append(file_sample)
        del reservoir, file_sample

    return pd.concat(chunks, ignore_index=True)

DEMO_MODE = True   # flip to False for full 1000-sentence run
N_PER_FILE = 10 if DEMO_MODE else 100
print(f'Mode: {"demo" if DEMO_MODE else "full"} — {N_PER_FILE} per file × 10 files = {N_PER_FILE * 10} total')

Mode: demo — 10 per file × 10 files = 100 total

In [6]:
df = sample_from_tsv('data/C4_200M/C4_200M.tsv-*', n_rows=N_PER_FILE)
src = df['original'].tolist()
gt  = df['ground_truth'].tolist()
print(f'Sampled {len(df)} rows total')
df.head(3)

Sampling files:   0%|          | 0/10 [00:00<?, ?it/s]

Sampling files:  10%|█         | 1/10 [01:51<16:41, 111.31s/it]

Sampling files:  20%|██        | 2/10 [03:30<13:51, 103.94s/it]

Sampling files:  30%|███       | 3/10 [05:08<11:49, 101.29s/it]

Sampling files:  40%|████      | 4/10 [06:47<10:01, 100.32s/it]

Sampling files:  50%|█████     | 5/10 [08:25<08:18, 99.72s/it]

Sampling files:  60%|██████    | 6/10 [10:04<06:38, 99.55s/it]

Sampling files:  70%|███████   | 7/10 [11:49<05:03, 101.32s/it]

Sampling files:  80%|████████  | 8/10 [13:36<03:25, 102.94s/it]

Sampling files:  90%|█████████ | 9/10 [15:21<01:43, 103.75s/it]

Sampling files: 100%|██████████| 10/10 [17:09<00:00, 105.07s/it]

Sampling files: 100%|██████████| 10/10 [17:09<00:00, 102.99s/it]

Sampled 100 rows total

,original,ground_truth
0,Vicinity and Keppel will they hold a 50 per ce...,Vicinity and Keppel will each hold a 50 per ce...
1,"Most smart contracts, it turns out, are not pe...","Most smart contracts, it turns out, are not pe..."
2,Is this the smallest conrtoller! door you’ve e...,Is this the smallest door controller you’ve ev...

## Shared Batch Generation Utilities

All prompt variants share the same batched generation loop.
The model receives `BATCH_SIZE` numbered sentences and returns one generated sentence per line.
Retry logic handles rate limits (exponential back-off) and output parse failures.

In [7]:
from openai import RateLimitError

BATCH_SIZE = 5
SLEEP_SEC  = 10

def make_batch_input(sentences):
    return '\n'.join(f'{i+1}. {s}' for i, s in enumerate(sentences))

def parse_batch_output(text, expected):
    """Extract one output line per input sentence from numbered LLM output."""
    lines = [
        re.sub(r'^[0-9]+[.)\s]+', '', l).strip()
        for l in text.strip().splitlines()
        if re.match(r'^[0-9]+[.)]', l.strip())
    ]
    if len(lines) == expected:
        return lines
    # fallback: model returned plain unnumbered lines
    fallback = [l.strip() for l in text.strip().splitlines() if l.strip()]
    if len(fallback) == expected:
        return fallback
    raise ValueError(f'Expected {expected} lines, got {len(lines)} numbered / {len(fallback)} plain:\n{text}')

def invoke_batch_with_retry(chain, sentences, max_retries=7, base_delay=10):
    batch_input = make_batch_input(sentences)
    last_error = None
    for attempt in range(max_retries):
        try:
            result = chain.invoke({'batch_input': batch_input})
            return parse_batch_output(result, len(sentences))
        except ValueError as e:
            last_error = e
            time.sleep(base_delay * (2 ** attempt))
        except RateLimitError as e:
            wait = 60 * (2 ** attempt)
            print(f'\nRate limit, retrying in {wait}s...')
            time.sleep(wait)
    raise RuntimeError(f'Failed after {max_retries} retries. Last: {last_error}')

def run_generation(chain, sentences, batch_size=BATCH_SIZE, sleep=SLEEP_SEC, desc='Generating'):
    batches = [sentences[i:i+batch_size] for i in range(0, len(sentences), batch_size)]
    results = []
    for batch in tqdm(batches, desc=desc):
        results.extend(invoke_batch_with_retry(chain, batch))
        time.sleep(sleep)
    return results

print('Batch utilities ready')

Batch utilities ready

## Prompt Variants

### 2.1 Zero-Shot Baseline

Instruction only — no examples. The model must infer the task from text alone.
Sets the **lower bound** for ablations.

**Expected weakness**: without examples the model may correct errors rather than replicate them,
or generate generic incorrect sentences that don't match C4 error distributions.

In [8]:
ZS_INSTR = (
    'You are a grammatical error generator. '
    'For each sentence below, write a completely NEW sentence on a different topic '
    'that contains the same type of grammatical error. '
    'Do NOT correct the given sentence — create an entirely new one. '
    'Return only the generated sentences, one per line, preserving the original numbering.'
)

zero_shot_chain = (
    ChatPromptTemplate.from_messages([('human', ZS_INSTR + '\n\n{batch_input}')])
    | llm
    | StrOutputParser()
)
print('Zero-shot chain ready')

Zero-shot chain ready

### 2.2 One-Shot

One SVA example shows the model the expected **input/output format**
(erroneous in → different erroneous out on a new topic) without revealing all error categories.

**Design choice**: single example from `gec_error_types.json` keeps it taxonomy-consistent
and cheap (short prompt). Main purpose is clarifying the format, not the error space.

In [9]:
ONE_SHOT_EX = (
    'Example:\n'
    'Input:  1. The group of students are going to the library.\n'
    'Output: 1. The team of engineers was arguing about their blueprints.\n\n'
)

one_shot_chain = (
    ChatPromptTemplate.from_messages([('human', ZS_INSTR + '\n\n' + ONE_SHOT_EX + '{batch_input}')])
    | llm
    | StrOutputParser()
)
print('One-shot chain ready')

One-shot chain ready

### 3 Few-Shot (Stratified by Error Type)

Two coverage levels from `gec_few_shot_examples.json → demonstrations`:

- **3-shot balanced**: SVA, article, verb_tense — three most frequent ERRANT categories in C4.
- **12-shot full**: one `(input, output)` demonstration per error type.

**Hypothesis**: more examples reduce hallucination (model correcting instead of replicating)
but add prompt length overhead → longer batch processing, smaller batch sizes needed.
Ablation will test whether 3→12 examples is worth the extra tokens.

In [10]:
def make_few_shot_block(pairs):
    """Format list of (input, output) pairs as a numbered examples block."""
    lines = []
    for i, (inp, out) in enumerate(pairs, 1):
        lines += [f'Example {i}:', f'Input:  {inp}', f'Output: {out}', '']
    return '\n'.join(lines)

FS_BASE_INSTR = (
    'You are a grammatical error generator. '
    'For each sentence below, write a completely NEW sentence on a different topic '
    'that contains the same type of grammatical error as the input. '
    'Do NOT correct the given sentence.\n'
    'Return only the generated sentences, one per line, preserving the numbering.\n\n'
)

def make_few_shot_chain(pairs, temperature=0.7):
    block = make_few_shot_block(pairs)
    prompt = ChatPromptTemplate.from_messages([
        ('human', FS_BASE_INSTR + block + 'Now generate for:\n{batch_input}')
    ])
    return prompt | make_llm(temperature) | StrOutputParser()

# Balanced 3-shot: SVA, article, verb_tense
pairs_3 = [
    (demonstrations[k]['input'], demonstrations[k]['output'])
    for k in ('subject_verb_agreement', 'article', 'verb_tense')
]

# Full 12-shot: one per error type (same order as gec_error_types.json)
pairs_12 = [
    (demonstrations[et['name']]['input'], demonstrations[et['name']]['output'])
    for et in error_types
]

few_shot_3_chain  = make_few_shot_chain(pairs_3)
few_shot_12_chain = make_few_shot_chain(pairs_12)
print(f'Few-shot chains ready:  3-shot ({len(pairs_3)} examples),  12-shot ({len(pairs_12)} examples)')

Few-shot chains ready:  3-shot (3 examples),  12-shot (12 examples)

### 4 Chain-of-Thought (CoT)

The model is asked to:
1. Name the grammatical error type in the input sentence.
2. Generate a new sentence with the same error type.

**Rationale**: naming the type acts as a soft constraint — it anchors the generation
to the right error category before producing the surface form.

**Expected benefit**: higher precision on specific error categories, fewer hallucinated corrections.

**Expected cost**: structured two-part output is harder to parse;
batch size must be smaller (3) to reduce parse failures.

Output format required: `[N] Error type: <type>` then `[N] Generated: <sentence>`.

In [11]:
COT_INSTR = (
    'You are a grammatical error generator. For each numbered sentence below:\n'
    '  Step 1: Identify the grammatical error type (e.g. subject-verb agreement, article, spelling).\n'
    '  Step 2: Write a completely NEW sentence on a different topic with the same error type.\n\n'
    'Use this exact format for each sentence:\n'
    '[N] Error type: <type>\n'
    '[N] Generated: <new sentence>\n\n'
    'Do NOT correct or rewrite the input sentence.\n'
)

cot_chain = (
    ChatPromptTemplate.from_messages([('human', COT_INSTR + '\n{batch_input}')])
    | make_llm(0.7)
    | StrOutputParser()
)

def parse_cot_output(text, expected):
    """Extract Generated: lines from CoT structured output."""
    generated = []
    for line in text.strip().splitlines():
        m = re.match(r'^\[[0-9]+\]\s*Generated:\s*(.+)', line.strip())
        if m:
            generated.append(m.group(1).strip())
    if len(generated) == expected:
        return generated
    # Fallback: any line containing 'Generated:'
    generated = [
        line.split('Generated:', 1)[1].strip()
        for line in text.strip().splitlines()
        if 'Generated:' in line
    ]
    if len(generated) == expected:
        return generated
    raise ValueError(f'CoT parse failed. Expected {expected}, got {len(generated)}:\n{text}')

def run_cot(sentences, batch_size=3, sleep=20, desc='CoT'):
    batches = [sentences[i:i+batch_size] for i in range(0, len(sentences), batch_size)]
    results = []
    failed_batches = []
    for batch_idx, batch in enumerate(tqdm(batches, desc=desc)):
        batch_input = make_batch_input(batch)
        success = False
        for attempt in range(7):
            try:
                out = cot_chain.invoke({'batch_input': batch_input})
                results.extend(parse_cot_output(out, len(batch)))
                success = True
                break
            except ValueError:
                time.sleep(10 * (2 ** attempt))
            except RateLimitError:
                time.sleep(60 * (2 ** attempt))
        if not success:
            # Keep length aligned so downstream cells never crash on mismatch.
            # Placeholders are easy to filter out before evaluation.
            results.extend(['[GENERATION FAILED]'] * len(batch))
            failed_batches.append(batch_idx)
        time.sleep(sleep)
    if failed_batches:
        print(f'  Warning: {len(failed_batches)} batch(es) used placeholders: idx {failed_batches}')
    return results

print('CoT chain ready')

CoT chain ready

## Generation Pipeline

Run all 5 variants on the same sample and save to individual CSVs.
CSVs are the checkpoint: if the kernel dies mid-run, re-load from CSV and skip re-generation.

> Tune `BATCH_SIZE` and `SLEEP_SEC` above if you hit rate limits on the free tier.
> For 12-shot and CoT, use `batch_size=3` to stay within token limits.

## Generation Pipeline

Each variant runs in its own cell — interrupt and resume individually without losing completed work.
Results checkpoint to CSV after each variant.

In [12]:
src = df['original'].tolist()
gt  = df['ground_truth'].tolist()
results = {}
print(f'{len(src)} sentences loaded')

100 sentences loaded

In [13]:
print('--- Zero-shot ---')
results['zero_shot'] = run_generation(zero_shot_chain, src, desc='Zero-shot')
pd.DataFrame({'original': src, 'generated': results['zero_shot'], 'ground_truth': gt}).to_csv('gen_zero_shot.csv', index=False)
print(f'Saved gen_zero_shot.csv  ({len(results["zero_shot"])} rows)')

--- Zero-shot ---

Zero-shot:   0%|          | 0/20 [00:00<?, ?it/s]

Zero-shot:   5%|▌         | 1/20 [01:03<19:59, 63.12s/it]

Zero-shot:  10%|█         | 2/20 [01:43<14:56, 49.82s/it]

Zero-shot:  15%|█▌        | 3/20 [03:11<19:02, 67.19s/it]

Zero-shot:  20%|██        | 4/20 [04:05<16:30, 61.90s/it]

Zero-shot:  25%|██▌       | 5/20 [04:48<13:47, 55.14s/it]

Zero-shot:  30%|███       | 6/20 [05:33<12:04, 51.78s/it]

Zero-shot:  35%|███▌      | 7/20 [06:16<10:37, 49.00s/it]

Zero-shot:  40%|████      | 8/20 [07:27<11:10, 55.86s/it]

Zero-shot:  45%|████▌     | 9/20 [08:23<10:15, 55.96s/it]

Zero-shot:  50%|█████     | 10/20 [09:11<08:52, 53.29s/it]

Zero-shot:  55%|█████▌    | 11/20 [10:37<09:31, 63.47s/it]

Zero-shot:  60%|██████    | 12/20 [11:52<08:54, 66.85s/it]

Zero-shot:  65%|██████▌   | 13/20 [12:25<06:36, 56.61s/it]

Zero-shot:  70%|███████   | 14/20 [14:13<07:14, 72.37s/it]

Zero-shot:  75%|███████▌  | 15/20 [15:05<05:30, 66.12s/it]

Zero-shot:  80%|████████  | 16/20 [15:52<04:01, 60.36s/it]

Zero-shot:  85%|████████▌ | 17/20 [16:44<02:53, 57.85s/it]

Zero-shot:  90%|█████████ | 18/20 [17:43<01:56, 58.25s/it]

Zero-shot:  95%|█████████▌| 19/20 [18:35<00:56, 56.31s/it]

Zero-shot: 100%|██████████| 20/20 [19:11<00:00, 50.08s/it]

Zero-shot: 100%|██████████| 20/20 [19:11<00:00, 57.56s/it]

Saved gen_zero_shot.csv  (100 rows)

In [14]:
print('--- One-shot ---')
results['one_shot'] = run_generation(one_shot_chain, src, desc='One-shot')
pd.DataFrame({'original': src, 'generated': results['one_shot'], 'ground_truth': gt}).to_csv('gen_one_shot.csv', index=False)
print(f'Saved gen_one_shot.csv  ({len(results["one_shot"])} rows)')

--- One-shot ---

One-shot:   0%|          | 0/20 [00:00<?, ?it/s]

One-shot:   5%|▌         | 1/20 [01:06<21:07, 66.71s/it]

One-shot:  10%|█         | 2/20 [02:24<22:02, 73.46s/it]

One-shot:  15%|█▌        | 3/20 [03:47<21:57, 77.51s/it]

One-shot:  20%|██        | 4/20 [05:42<24:38, 92.42s/it]

One-shot:  25%|██▌       | 5/20 [07:37<25:08, 100.54s/it]

One-shot:  30%|███       | 6/20 [08:38<20:19, 87.12s/it]

One-shot:  35%|███▌      | 7/20 [09:34<16:41, 77.05s/it]

One-shot:  40%|████      | 8/20 [10:48<15:12, 76.07s/it]

One-shot:  45%|████▌     | 9/20 [11:49<13:04, 71.32s/it]

One-shot:  50%|█████     | 10/20 [12:37<10:40, 64.10s/it]

One-shot:  55%|█████▌    | 11/20 [13:29<09:01, 60.22s/it]

One-shot:  60%|██████    | 12/20 [14:12<07:20, 55.03s/it]

One-shot:  65%|██████▌   | 13/20 [14:54<05:58, 51.27s/it]

One-shot:  70%|███████   | 14/20 [16:11<05:53, 58.93s/it]

One-shot:  75%|███████▌  | 15/20 [17:00<04:39, 55.94s/it]

One-shot:  80%|████████  | 16/20 [18:07<03:57, 59.31s/it]

One-shot:  85%|████████▌ | 17/20 [19:06<02:57, 59.07s/it]

One-shot:  90%|█████████ | 18/20 [20:32<02:14, 67.38s/it]

One-shot:  95%|█████████▌| 19/20 [21:59<01:13, 73.30s/it]

One-shot: 100%|██████████| 20/20 [23:14<00:00, 73.73s/it]

One-shot: 100%|██████████| 20/20 [23:14<00:00, 69.73s/it]

Saved gen_one_shot.csv  (100 rows)

In [15]:
print('--- Few-shot 3 ---')
results['few_shot_3'] = run_generation(few_shot_3_chain, src, batch_size=3, sleep=15, desc='Few-shot-3')
pd.DataFrame({'original': src, 'generated': results['few_shot_3'], 'ground_truth': gt}).to_csv('gen_few_shot_3.csv', index=False)
print(f'Saved gen_few_shot_3.csv  ({len(results["few_shot_3"])} rows)')

--- Few-shot 3 ---

Few-shot-3:   0%|          | 0/34 [00:00<?, ?it/s]

Few-shot-3:   3%|▎         | 1/34 [01:35<52:16, 95.05s/it]

Few-shot-3:   6%|▌         | 2/34 [02:38<40:52, 76.63s/it]

Few-shot-3:   9%|▉         | 3/34 [03:31<33:55, 65.65s/it]

Few-shot-3:  12%|█▏        | 4/34 [04:50<35:23, 70.79s/it]

Few-shot-3:  15%|█▍        | 5/34 [05:43<31:09, 64.45s/it]

Few-shot-3:  18%|█▊        | 6/34 [06:59<32:01, 68.63s/it]

Few-shot-3:  21%|██        | 7/34 [08:08<30:51, 68.58s/it]

Few-shot-3:  24%|██▎       | 8/34 [11:19<46:40, 107.71s/it]

Few-shot-3:  26%|██▋       | 9/34 [14:24<54:54, 131.76s/it]

Few-shot-3:  29%|██▉       | 10/34 [15:04<41:24, 103.51s/it]

Few-shot-3:  32%|███▏      | 11/34 [15:54<33:22, 87.07s/it]

Few-shot-3:  35%|███▌      | 12/34 [16:48<28:09, 76.82s/it]

Few-shot-3:  38%|███▊      | 13/34 [17:56<26:00, 74.33s/it]

Few-shot-3:  41%|████      | 14/34 [18:51<22:50, 68.52s/it]

Few-shot-3:  44%|████▍     | 15/34 [19:24<18:15, 57.67s/it]

Few-shot-3:  47%|████▋     | 16/34 [20:07<15:58, 53.25s/it]

Few-shot-3:  50%|█████     | 17/34 [21:25<17:13, 60.77s/it]

Few-shot-3:  53%|█████▎    | 18/34 [22:18<15:33, 58.36s/it]

Few-shot-3:  56%|█████▌    | 19/34 [23:39<16:17, 65.18s/it]

Few-shot-3:  59%|█████▉    | 20/34 [25:27<18:12, 78.05s/it]

Few-shot-3:  62%|██████▏   | 21/34 [26:37<16:25, 75.80s/it]

Few-shot-3:  65%|██████▍   | 22/34 [28:25<17:03, 85.33s/it]

Few-shot-3:  68%|██████▊   | 23/34 [29:21<14:03, 76.67s/it]

Few-shot-3:  71%|███████   | 24/34 [30:38<12:45, 76.57s/it]

Few-shot-3:  74%|███████▎  | 25/34 [31:11<09:31, 63.52s/it]

Few-shot-3:  76%|███████▋  | 26/34 [32:31<09:07, 68.49s/it]

Few-shot-3:  79%|███████▉  | 27/34 [33:46<08:13, 70.57s/it]

Few-shot-3:  82%|████████▏ | 28/34 [34:14<05:46, 57.75s/it]

Few-shot-3:  85%|████████▌ | 29/34 [35:04<04:36, 55.30s/it]

Few-shot-3:  88%|████████▊ | 30/34 [35:59<03:41, 55.37s/it]

Few-shot-3:  91%|█████████ | 31/34 [37:30<03:17, 65.86s/it]

Few-shot-3:  94%|█████████▍| 32/34 [38:00<01:50, 55.24s/it]

Few-shot-3:  97%|█████████▋| 33/34 [39:34<01:06, 66.74s/it]

Few-shot-3: 100%|██████████| 34/34 [40:16<00:00, 59.41s/it]

Few-shot-3: 100%|██████████| 34/34 [40:16<00:00, 71.07s/it]

Saved gen_few_shot_3.csv  (100 rows)

In [16]:
print('--- Few-shot 12 ---')
results['few_shot_12'] = run_generation(few_shot_12_chain, src, batch_size=3, sleep=20, desc='Few-shot-12')
pd.DataFrame({'original': src, 'generated': results['few_shot_12'], 'ground_truth': gt}).to_csv('gen_few_shot_12.csv', index=False)
print(f'Saved gen_few_shot_12.csv  ({len(results["few_shot_12"])} rows)')

--- Few-shot 12 ---

Few-shot-12:   0%|          | 0/34 [00:00<?, ?it/s]

Few-shot-12:   3%|▎         | 1/34 [01:29<49:05, 89.25s/it]

Few-shot-12:   6%|▌         | 2/34 [02:12<33:12, 62.26s/it]

Few-shot-12:   9%|▉         | 3/34 [03:20<33:34, 65.00s/it]

Few-shot-12:  12%|█▏        | 4/34 [03:59<27:15, 54.52s/it]

Few-shot-12:  15%|█▍        | 5/34 [05:02<27:54, 57.74s/it]

Few-shot-12:  18%|█▊        | 6/34 [06:58<36:06, 77.37s/it]

Few-shot-12:  21%|██        | 7/34 [08:17<35:06, 78.01s/it]

Few-shot-12:  24%|██▎       | 8/34 [10:28<41:09, 94.99s/it]

Few-shot-12:  26%|██▋       | 9/34 [11:28<34:58, 83.93s/it]

Few-shot-12:  29%|██▉       | 10/34 [13:14<36:20, 90.84s/it]

Few-shot-12:  32%|███▏      | 11/34 [13:58<29:18, 76.47s/it]

Few-shot-12:  35%|███▌      | 12/34 [15:35<30:18, 82.64s/it]

Few-shot-12:  38%|███▊      | 13/34 [16:27<25:39, 73.30s/it]

Few-shot-12:  41%|████      | 14/34 [18:30<29:26, 88.32s/it]

Few-shot-12:  44%|████▍     | 15/34 [21:35<37:13, 117.54s/it]

Few-shot-12:  47%|████▋     | 16/34 [22:24<29:05, 96.98s/it]

Few-shot-12:  50%|█████     | 17/34 [23:09<23:01, 81.26s/it]

Few-shot-12:  53%|█████▎    | 18/34 [24:22<21:01, 78.87s/it]

Few-shot-12:  56%|█████▌    | 19/34 [25:24<18:24, 73.60s/it]

Few-shot-12:  59%|█████▉    | 20/34 [28:48<26:20, 112.88s/it]

Few-shot-12:  62%|██████▏   | 21/34 [29:29<19:45, 91.21s/it]

Few-shot-12:  65%|██████▍   | 22/34 [32:26<23:25, 117.11s/it]

Few-shot-12:  68%|██████▊   | 23/34 [34:39<22:18, 121.70s/it]

Few-shot-12:  71%|███████   | 24/34 [36:19<19:11, 115.19s/it]

Few-shot-12:  74%|███████▎  | 25/34 [37:07<14:16, 95.17s/it]

Few-shot-12:  76%|███████▋  | 26/34 [38:38<12:31, 93.91s/it]

Few-shot-12:  79%|███████▉  | 27/34 [39:59<10:29, 89.88s/it]

Few-shot-12:  82%|████████▏ | 28/34 [40:41<07:34, 75.77s/it]

Few-shot-12:  85%|████████▌ | 29/34 [44:33<10:12, 122.44s/it]

Few-shot-12:  88%|████████▊ | 30/34 [45:38<07:01, 105.41s/it]

Few-shot-12:  91%|█████████ | 31/34 [46:38<04:34, 91.53s/it]

Few-shot-12:  94%|█████████▍| 32/34 [47:35<02:42, 81.21s/it]

Few-shot-12:  97%|█████████▋| 33/34 [48:50<01:19, 79.40s/it]

Few-shot-12: 100%|██████████| 34/34 [49:14<00:00, 62.68s/it]

Few-shot-12: 100%|██████████| 34/34 [49:14<00:00, 86.88s/it]

Saved gen_few_shot_12.csv  (100 rows)

In [17]:
print('--- CoT ---')
results['cot'] = run_cot(src)
pd.DataFrame({'original': src, 'generated': results['cot'], 'ground_truth': gt}).to_csv('gen_cot.csv', index=False)
print(f'Saved gen_cot.csv  ({len(results["cot"])} rows)')

--- CoT ---

CoT:   0%|          | 0/34 [00:00<?, ?it/s]

CoT:   3%|▎         | 1/34 [00:47<26:14, 47.72s/it]

CoT:   6%|▌         | 2/34 [01:25<22:12, 41.64s/it]

CoT:   9%|▉         | 3/34 [02:22<25:08, 48.67s/it]

CoT:  12%|█▏        | 4/34 [03:41<30:21, 60.71s/it]

CoT:  15%|█▍        | 5/34 [04:39<28:51, 59.69s/it]

CoT:  18%|█▊        | 6/34 [05:42<28:27, 60.96s/it]

CoT:  21%|██        | 7/34 [06:51<28:33, 63.47s/it]

CoT:  24%|██▎       | 8/34 [07:37<25:06, 57.96s/it]

CoT:  26%|██▋       | 9/34 [08:32<23:45, 57.00s/it]

CoT:  29%|██▉       | 10/34 [09:21<21:47, 54.49s/it]

CoT:  32%|███▏      | 11/34 [10:04<19:34, 51.05s/it]

CoT:  35%|███▌      | 12/34 [11:12<20:33, 56.08s/it]

CoT:  38%|███▊      | 13/34 [12:03<19:09, 54.74s/it]

CoT:  41%|████      | 14/34 [12:57<18:08, 54.43s/it]

CoT:  44%|████▍     | 15/34 [14:01<18:09, 57.32s/it]

CoT:  47%|████▋     | 16/34 [15:10<18:12, 60.72s/it]

CoT:  50%|█████     | 17/34 [16:05<16:43, 59.05s/it]

CoT:  53%|█████▎    | 18/34 [16:42<13:59, 52.49s/it]

CoT:  56%|█████▌    | 19/34 [17:29<12:43, 50.89s/it]

CoT:  59%|█████▉    | 20/34 [18:11<11:15, 48.23s/it]

CoT:  62%|██████▏   | 21/34 [19:08<10:59, 50.75s/it]

CoT:  65%|██████▍   | 22/34 [20:02<10:20, 51.73s/it]

CoT:  68%|██████▊   | 23/34 [20:57<09:42, 52.94s/it]

CoT:  71%|███████   | 24/34 [22:22<10:24, 62.41s/it]

CoT:  74%|███████▎  | 25/34 [23:07<08:34, 57.16s/it]

CoT:  76%|███████▋  | 26/34 [23:47<06:57, 52.17s/it]

CoT:  79%|███████▉  | 27/34 [24:27<05:37, 48.24s/it]

CoT:  82%|████████▏ | 28/34 [25:09<04:38, 46.39s/it]

CoT:  85%|████████▌ | 29/34 [25:50<03:43, 44.77s/it]

CoT:  88%|████████▊ | 30/34 [26:38<03:03, 45.75s/it]

CoT:  91%|█████████ | 31/34 [27:43<02:35, 51.70s/it]

CoT:  94%|█████████▍| 32/34 [28:23<01:36, 48.28s/it]

CoT:  97%|█████████▋| 33/34 [30:06<01:04, 64.52s/it]

CoT: 100%|██████████| 34/34 [30:41<00:00, 55.72s/it]

CoT: 100%|██████████| 34/34 [30:41<00:00, 54.16s/it]

Saved gen_cot.csv  (100 rows)

In [18]:
# Reload any variants from CSV in case kernel was restarted mid-run
VARIANTS = ['zero_shot', 'one_shot', 'few_shot_3', 'few_shot_12', 'cot']
for v in VARIANTS:
    if v not in results:
        import os
        if os.path.exists(f'gen_{v}.csv'):
            df_v = pd.read_csv(f'gen_{v}.csv')
            results[v] = df_v['generated'].tolist()
            print(f'Reloaded {v} from CSV ({len(results[v])} rows)')
        else:
            print(f'Missing: {v} — run the cell above')
print('results keys:', list(results.keys()))

results keys: ['zero_shot', 'one_shot', 'few_shot_3', 'few_shot_12', 'cot']

## T5 GEC Correction  (B → C)

Use `vennify/t5-base-grammar-correction` (seq2seq T5) to correct LLM-generated sentences.

**Why seq2seq directly, not `pipeline('text-generation')`**:  
transformers 5.x `text-generation` pipeline only supports causal LMs;
T5 requires `AutoModelForSeq2SeqLM` with `.generate()`.  
The input prefix `"grammar: "` is required by the model's training format.

In [19]:
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

T5_MODEL = 'vennify/t5-base-grammar-correction'
t5_tok = AutoTokenizer.from_pretrained(T5_MODEL)
t5_mdl = AutoModelForSeq2SeqLM.from_pretrained(T5_MODEL)
t5_mdl.eval()

def correct_sentences(sentences, batch_size=8, prefix='grammar: '):
    results = []
    for i in tqdm(range(0, len(sentences), batch_size), desc='T5 GEC'):
        batch = [prefix + s for s in sentences[i:i+batch_size]]
        inputs = t5_tok(batch, return_tensors='pt', padding=True, truncation=True, max_length=128)
        with torch.no_grad():
            outputs = t5_mdl.generate(**inputs, max_new_tokens=128)
        results.extend(t5_tok.batch_decode(outputs, skip_special_tokens=True))
    return results

print('T5 model loaded')

Loading weights:   0%|          | 0/260 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 260/260 [00:00<00:00, 11875.02it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

The tied weights mapping and config for this model specifies to tie shared.weight to decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

T5 model loaded

In [20]:
corrected = {}
for variant in results:
    print(f'\nRunning T5 on: {variant}')
    df_v = pd.read_csv(f'gen_{variant}.csv')
    df_v['t5_corrected'] = correct_sentences(df_v['generated'].tolist())
    df_v.to_csv(f'gen_{variant}_corrected.csv', index=False)
    corrected[variant] = df_v
    print(f'  orig:  {df_v["generated"].iloc[0]}')
    print(f'  fixed: {df_v["t5_corrected"].iloc[0]}')

Running T5 on: zero_shot

T5 GEC:   0%|          | 0/13 [00:00<?, ?it/s]

T5 GEC:   8%|▊         | 1/13 [00:06<01:19,  6.60s/it]

T5 GEC:  15%|█▌        | 2/13 [00:09<00:48,  4.45s/it]

T5 GEC:  23%|██▎       | 3/13 [00:17<00:58,  5.87s/it]

T5 GEC:  31%|███       | 4/13 [00:24<00:59,  6.56s/it]

T5 GEC:  38%|███▊      | 5/13 [00:26<00:39,  4.90s/it]

T5 GEC:  46%|████▌     | 6/13 [00:27<00:25,  3.65s/it]

T5 GEC:  54%|█████▍    | 7/13 [00:30<00:20,  3.45s/it]

T5 GEC:  62%|██████▏   | 8/13 [00:37<00:22,  4.43s/it]

T5 GEC:  69%|██████▉   | 9/13 [00:50<00:28,  7.01s/it]

T5 GEC:  77%|███████▋  | 10/13 [00:51<00:15,  5.25s/it]

T5 GEC:  85%|████████▍ | 11/13 [00:53<00:08,  4.39s/it]

T5 GEC:  92%|█████████▏| 12/13 [01:03<00:06,  6.04s/it]

T5 GEC: 100%|██████████| 13/13 [01:05<00:00,  4.76s/it]

T5 GEC: 100%|██████████| 13/13 [01:05<00:00,  5.04s/it]

  orig:  The chef and his assistant will they prepares a five-course meal and the guests will enjoys the dessert.
  fixed: The chef and his assistant will prepare a five-course meal and the guests will enjoy the dessert.

Running T5 on: one_shot

T5 GEC:   0%|          | 0/13 [00:00<?, ?it/s]

T5 GEC:   8%|▊         | 1/13 [00:01<00:17,  1.48s/it]

T5 GEC:  15%|█▌        | 2/13 [00:06<00:41,  3.75s/it]

T5 GEC:  23%|██▎       | 3/13 [00:08<00:29,  2.94s/it]

T5 GEC:  31%|███       | 4/13 [00:11<00:24,  2.77s/it]

T5 GEC:  38%|███▊      | 5/13 [00:13<00:21,  2.73s/it]

T5 GEC:  46%|████▌     | 6/13 [00:16<00:17,  2.54s/it]

T5 GEC:  54%|█████▍    | 7/13 [00:18<00:15,  2.58s/it]

T5 GEC:  62%|██████▏   | 8/13 [00:20<00:11,  2.28s/it]

T5 GEC:  69%|██████▉   | 9/13 [00:22<00:09,  2.33s/it]

T5 GEC:  77%|███████▋  | 10/13 [00:26<00:07,  2.60s/it]

T5 GEC:  85%|████████▍ | 11/13 [00:27<00:04,  2.17s/it]

T5 GEC:  92%|█████████▏| 12/13 [00:29<00:02,  2.07s/it]

T5 GEC: 100%|██████████| 13/13 [00:31<00:00,  2.07s/it]

T5 GEC: 100%|██████████| 13/13 [00:31<00:00,  2.40s/it]

  orig:  The committee members will they approve the budget and each member has to signs the agreement.
  fixed: The committee members will approve the budget and each member has to sign the agreement.

Running T5 on: few_shot_3

T5 GEC:   0%|          | 0/13 [00:00<?, ?it/s]

T5 GEC:   8%|▊         | 1/13 [00:03<00:46,  3.91s/it]

T5 GEC:  15%|█▌        | 2/13 [00:05<00:30,  2.82s/it]

T5 GEC:  23%|██▎       | 3/13 [00:09<00:30,  3.08s/it]

T5 GEC:  31%|███       | 4/13 [00:12<00:27,  3.01s/it]

T5 GEC:  38%|███▊      | 5/13 [00:17<00:29,  3.69s/it]

T5 GEC:  46%|████▌     | 6/13 [00:18<00:19,  2.73s/it]

T5 GEC:  54%|█████▍    | 7/13 [00:20<00:15,  2.61s/it]

T5 GEC:  62%|██████▏   | 8/13 [00:21<00:10,  2.06s/it]

T5 GEC:  69%|██████▉   | 9/13 [00:24<00:09,  2.39s/it]

T5 GEC:  77%|███████▋  | 10/13 [00:26<00:06,  2.27s/it]

T5 GEC:  85%|████████▍ | 11/13 [00:27<00:03,  1.97s/it]

T5 GEC:  92%|█████████▏| 12/13 [00:29<00:01,  1.78s/it]

T5 GEC: 100%|██████████| 13/13 [00:29<00:00,  1.48s/it]

T5 GEC: 100%|██████████| 13/13 [00:29<00:00,  2.29s/it]

  orig:  The committee and the board will they approve the budget and the manager will signs the contract.
  fixed: The committee and the board will approve the budget and the manager will sign the contract.

Running T5 on: few_shot_12

T5 GEC:   0%|          | 0/13 [00:00<?, ?it/s]

T5 GEC:   8%|▊         | 1/13 [00:00<00:10,  1.15it/s]

T5 GEC:  15%|█▌        | 2/13 [00:02<00:16,  1.52s/it]

T5 GEC:  23%|██▎       | 3/13 [00:04<00:14,  1.46s/it]

T5 GEC:  31%|███       | 4/13 [00:05<00:12,  1.36s/it]

T5 GEC:  38%|███▊      | 5/13 [00:06<00:10,  1.31s/it]

T5 GEC:  46%|████▌     | 6/13 [00:08<00:09,  1.34s/it]

T5 GEC:  54%|█████▍    | 7/13 [00:10<00:10,  1.73s/it]

T5 GEC:  62%|██████▏   | 8/13 [00:11<00:07,  1.47s/it]

T5 GEC:  69%|██████▉   | 9/13 [00:13<00:06,  1.57s/it]

T5 GEC:  77%|███████▋  | 10/13 [00:14<00:04,  1.50s/it]

T5 GEC:  85%|████████▍ | 11/13 [00:15<00:02,  1.39s/it]

T5 GEC:  92%|█████████▏| 12/13 [00:17<00:01,  1.61s/it]

T5 GEC: 100%|██████████| 13/13 [00:20<00:00,  1.90s/it]

T5 GEC: 100%|██████████| 13/13 [00:20<00:00,  1.58s/it]

  orig:  The committee members has approved the new policy.
  fixed: The committee members have approved the new policy.

Running T5 on: cot

T5 GEC:   0%|          | 0/13 [00:00<?, ?it/s]

T5 GEC:   8%|▊         | 1/13 [00:00<00:11,  1.04it/s]

T5 GEC:  15%|█▌        | 2/13 [00:02<00:14,  1.30s/it]

T5 GEC:  23%|██▎       | 3/13 [00:04<00:16,  1.65s/it]

T5 GEC:  31%|███       | 4/13 [00:06<00:14,  1.57s/it]

T5 GEC:  38%|███▊      | 5/13 [00:07<00:11,  1.42s/it]

T5 GEC:  46%|████▌     | 6/13 [00:08<00:09,  1.30s/it]

T5 GEC:  54%|█████▍    | 7/13 [00:09<00:06,  1.14s/it]

T5 GEC:  62%|██████▏   | 8/13 [00:10<00:05,  1.16s/it]

T5 GEC:  69%|██████▉   | 9/13 [00:13<00:07,  1.96s/it]

T5 GEC:  77%|███████▋  | 10/13 [00:15<00:05,  1.74s/it]

T5 GEC:  85%|████████▍ | 11/13 [00:16<00:03,  1.51s/it]

T5 GEC:  92%|█████████▏| 12/13 [00:17<00:01,  1.49s/it]

T5 GEC: 100%|██████████| 13/13 [00:18<00:00,  1.27s/it]

T5 GEC: 100%|██████████| 13/13 [00:18<00:00,  1.42s/it]

  orig:  The group of students are going to the museum tomorrow.
  fixed: The group of students are going to the museum tomorrow.

## Evaluation

Three complementary metrics:

| Metric | What it measures | Implementation |
|--------|-----------------|----------------|
| CoLA | Grammatical acceptability of A, B, C | `textattack/bert-base-uncased-CoLA` |
| Semantic similarity | Topic preservation: original ↔ generated | TF-IDF cosine (sklearn, no extra deps) |
| ERRANT F0.5 | Error-type distribution alignment vs C4 reference | `errant` package |

**Key assertions** (per variant):  
- `CoLA(B) < CoLA(A)` — generated sentences are erroneous (LLM task success)  
- `CoLA(C) > CoLA(B)` — T5 genuinely improves B (T5 task success)

### CoLA Scores

- **A** = C4 original (already erroneous — erroneous baseline)
- **B** = LLM-generated (should be erroneous: `CoLA(B) ≤ CoLA(A)`)
- **C** = T5-corrected B (should improve: `CoLA(C) > CoLA(B)`)

CoLA outputs binary acceptability (1 = acceptable, 0 = unacceptable).
We compute the mean over each set as a grammaticality rate.

In [21]:
from transformers import pipeline as hf_pipeline

device = 0 if torch.cuda.is_available() else -1
cola_scorer = hf_pipeline(
    'text-classification',
    model='textattack/bert-base-uncased-CoLA',
    device=device,
)

def cola_scores(texts, batch_size=32):
    """Return list of 1.0 (acceptable) or 0.0 (unacceptable) per sentence."""
    scores = []
    for i in tqdm(range(0, len(texts), batch_size), desc='CoLA'):
        preds = cola_scorer(texts[i:i+batch_size], truncation=True, max_length=128)
        scores.extend(1.0 if p['label'] == 'acceptable' else 0.0 for p in preds)
    return scores

cola_results = {}
for variant, df_v in corrected.items():
    a = cola_scores(df_v['original'].tolist())
    b = cola_scores(df_v['generated'].tolist())
    c = cola_scores(df_v['t5_corrected'].tolist())
    cola_results[variant] = {
        'cola_A': round(np.mean(a), 3),
        'cola_B': round(np.mean(b), 3),
        'cola_C': round(np.mean(c), 3),
        'B<A': bool(np.mean(b) < np.mean(a)),
        'C>B': bool(np.mean(c) > np.mean(b)),
    }

cola_df = pd.DataFrame(cola_results).T
print('CoLA results (higher = more grammatically acceptable):')
print(cola_df.to_string())

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 16212.91it/s]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:03<00:09,  3.17s/it]

CoLA:  50%|█████     | 2/4 [00:05<00:05,  2.57s/it]

CoLA:  75%|███████▌  | 3/4 [00:09<00:03,  3.38s/it]

CoLA: 100%|██████████| 4/4 [00:10<00:00,  2.18s/it]

CoLA: 100%|██████████| 4/4 [00:10<00:00,  2.51s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:02<00:08,  2.72s/it]

CoLA:  50%|█████     | 2/4 [00:06<00:06,  3.29s/it]

CoLA:  75%|███████▌  | 3/4 [00:09<00:02,  2.98s/it]

CoLA: 100%|██████████| 4/4 [00:09<00:00,  1.90s/it]

CoLA: 100%|██████████| 4/4 [00:09<00:00,  2.31s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:02<00:06,  2.30s/it]

CoLA:  50%|█████     | 2/4 [00:04<00:04,  2.19s/it]

CoLA:  75%|███████▌  | 3/4 [00:06<00:02,  2.14s/it]

CoLA: 100%|██████████| 4/4 [00:06<00:00,  1.37s/it]

CoLA: 100%|██████████| 4/4 [00:06<00:00,  1.67s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:03<00:09,  3.11s/it]

CoLA:  50%|█████     | 2/4 [00:05<00:05,  2.82s/it]

CoLA:  75%|███████▌  | 3/4 [00:08<00:02,  2.70s/it]

CoLA: 100%|██████████| 4/4 [00:08<00:00,  1.79s/it]

CoLA: 100%|██████████| 4/4 [00:08<00:00,  2.17s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:01<00:05,  1.86s/it]

CoLA:  50%|█████     | 2/4 [00:03<00:03,  1.75s/it]

CoLA:  75%|███████▌  | 3/4 [00:05<00:01,  1.71s/it]

CoLA: 100%|██████████| 4/4 [00:05<00:00,  1.11s/it]

CoLA: 100%|██████████| 4/4 [00:05<00:00,  1.34s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:01<00:04,  1.64s/it]

CoLA:  50%|█████     | 2/4 [00:03<00:04,  2.06s/it]

CoLA:  75%|███████▌  | 3/4 [00:05<00:01,  1.91s/it]

CoLA: 100%|██████████| 4/4 [00:05<00:00,  1.23s/it]

CoLA: 100%|██████████| 4/4 [00:05<00:00,  1.48s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:02<00:06,  2.27s/it]

CoLA:  50%|█████     | 2/4 [00:04<00:04,  2.16s/it]

CoLA:  75%|███████▌  | 3/4 [00:07<00:02,  2.51s/it]

CoLA: 100%|██████████| 4/4 [00:07<00:00,  1.60s/it]

CoLA: 100%|██████████| 4/4 [00:07<00:00,  1.87s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:01<00:04,  1.56s/it]

CoLA:  50%|█████     | 2/4 [00:02<00:02,  1.41s/it]

CoLA:  75%|███████▌  | 3/4 [00:04<00:01,  1.40s/it]

CoLA: 100%|██████████| 4/4 [00:04<00:00,  1.10it/s]

CoLA: 100%|██████████| 4/4 [00:04<00:00,  1.10s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:02<00:06,  2.29s/it]

CoLA:  50%|█████     | 2/4 [00:04<00:04,  2.31s/it]

CoLA:  75%|███████▌  | 3/4 [00:06<00:01,  1.97s/it]

CoLA: 100%|██████████| 4/4 [00:06<00:00,  1.25s/it]

CoLA: 100%|██████████| 4/4 [00:06<00:00,  1.58s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:01<00:05,  2.00s/it]

CoLA:  50%|█████     | 2/4 [00:04<00:04,  2.24s/it]

CoLA:  75%|███████▌  | 3/4 [00:07<00:02,  2.56s/it]

CoLA: 100%|██████████| 4/4 [00:07<00:00,  1.79s/it]

CoLA: 100%|██████████| 4/4 [00:07<00:00,  1.99s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:02<00:07,  2.39s/it]

CoLA:  50%|█████     | 2/4 [00:03<00:03,  1.82s/it]

CoLA:  75%|███████▌  | 3/4 [00:05<00:01,  1.55s/it]

CoLA: 100%|██████████| 4/4 [00:05<00:00,  1.07s/it]

CoLA: 100%|██████████| 4/4 [00:05<00:00,  1.34s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:02<00:08,  2.73s/it]

CoLA:  50%|█████     | 2/4 [00:04<00:03,  1.94s/it]

CoLA:  75%|███████▌  | 3/4 [00:05<00:01,  1.67s/it]

CoLA: 100%|██████████| 4/4 [00:05<00:00,  1.07s/it]

CoLA: 100%|██████████| 4/4 [00:05<00:00,  1.40s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:02<00:06,  2.27s/it]

CoLA:  50%|█████     | 2/4 [00:03<00:03,  1.86s/it]

CoLA:  75%|███████▌  | 3/4 [00:06<00:02,  2.32s/it]

CoLA: 100%|██████████| 4/4 [00:06<00:00,  1.49s/it]

CoLA: 100%|██████████| 4/4 [00:06<00:00,  1.73s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:01<00:03,  1.32s/it]

CoLA:  50%|█████     | 2/4 [00:02<00:02,  1.40s/it]

CoLA:  75%|███████▌  | 3/4 [00:04<00:01,  1.40s/it]

CoLA: 100%|██████████| 4/4 [00:04<00:00,  1.03it/s]

CoLA: 100%|██████████| 4/4 [00:04<00:00,  1.12s/it]

CoLA:   0%|          | 0/4 [00:00<?, ?it/s]

CoLA:  25%|██▌       | 1/4 [00:01<00:04,  1.48s/it]

CoLA:  50%|█████     | 2/4 [00:02<00:02,  1.40s/it]

CoLA:  75%|███████▌  | 3/4 [00:04<00:01,  1.37s/it]

CoLA: 100%|██████████| 4/4 [00:04<00:00,  1.12it/s]

CoLA: 100%|██████████| 4/4 [00:04<00:00,  1.08s/it]

CoLA results (higher = more grammatically acceptable):
            cola_A cola_B cola_C    B<A    C>B
zero_shot      0.0    0.0    0.0  False  False
one_shot       0.0    0.0    0.0  False  False
few_shot_3     0.0    0.0    0.0  False  False
few_shot_12    0.0    0.0    0.0  False  False
cot            0.0    0.0    0.0  False  False

### Semantic Similarity

TF-IDF cosine similarity between the original C4 sentence (A) and the LLM-generated sentence (B).

**Implementation choice**: sklearn TF-IDF avoids adding `sentence-transformers` as a dependency
(not in `requirements.txt`). It's a lightweight proxy — captures vocabulary overlap,
not deep semantics, but sufficient to flag extreme cases.

**Target range**: 0.15 – 0.50. Too high (> 0.8) = paraphrase; too low (< 0.1) = off-topic.

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity as cos_sim

def tfidf_sim(texts_a, texts_b):
    """Pairwise TF-IDF cosine similarity between two aligned lists of texts."""
    all_texts = texts_a + texts_b
    tfidf = TfidfVectorizer().fit_transform(all_texts)
    n = len(texts_a)
    return [float(cos_sim(tfidf[i], tfidf[n + i])[0, 0]) for i in range(n)]

sem_results = {}
for variant, df_v in corrected.items():
    sims = tfidf_sim(df_v['original'].tolist(), df_v['generated'].tolist())
    sem_results[variant] = {
        'mean_sim': round(np.mean(sims), 3),
        'std_sim':  round(np.std(sims),  3),
    }

sem_df = pd.DataFrame(sem_results).T
print('Semantic similarity  original → generated  (TF-IDF cosine):')
print(sem_df.to_string())

Semantic similarity  original → generated  (TF-IDF cosine):
             mean_sim  std_sim
zero_shot       0.112    0.121
one_shot        0.094    0.106
few_shot_3      0.089    0.135
few_shot_12     0.054    0.068
cot             0.033    0.041

### ERRANT — Error-Type Distribution

ERRANT annotates grammatical edits and classifies them into ERRANT types (R:SVA, U:ART, M:PREP, etc.).

**What we compute**:
1. **Reference distribution** — edit types in C4 original (A) → ground_truth corrections
2. **Hypothesis distribution** — edit types in LLM-generated (B) → T5-corrected (C)
3. **F0.5 on normalized type distributions** — precision-weighted overlap

**Why F0.5?** Standard GEC metric; weights precision 2× recall.
Here: generating the *right error types* (precision) matters more than generating *all* types (recall).

**Interpretation**: high F0.5 = LLM generates the same kinds of errors as the real C4 dataset.

In [23]:
import spacy, errant

# Download spacy model if missing
try:
    spacy.load('en_core_web_sm')
except OSError:
    import subprocess
    subprocess.run(['python', '-m', 'spacy', 'download', 'en_core_web_sm'], check=True)

annotator = errant.load('en')

def get_edits(src_sent, tgt_sent):
    orig = annotator.parse(src_sent)
    cor  = annotator.parse(tgt_sent)
    return annotator.annotate(orig, cor)

def edit_type_dist(edit_lists):
    """Normalized error-type distribution over a list of edit lists."""
    from collections import Counter
    counter = Counter(e.type for edits in edit_lists for e in edits)
    total = sum(counter.values()) or 1
    return {k: v / total for k, v in counter.items()}

def dist_f05(hyp_dist, ref_dist):
    """F0.5 on normalized error-type distributions."""
    types = set(hyp_dist) | set(ref_dist)
    tp = sum(min(hyp_dist.get(t, 0), ref_dist.get(t, 0)) for t in types)
    fp = sum(max(hyp_dist.get(t, 0) - ref_dist.get(t, 0), 0) for t in types)
    fn = sum(max(ref_dist.get(t, 0) - hyp_dist.get(t, 0), 0) for t in types)
    p  = tp / (tp + fp) if tp + fp > 0 else 0
    r  = tp / (tp + fn) if tp + fn > 0 else 0
    return (1.25 * p * r) / (0.25 * p + r) if 0.25 * p + r > 0 else 0

# Reference distribution: C4 original → C4 ground_truth
first_df = corrected[list(corrected)[0]]
ref_edits = [
    get_edits(o, g)
    for o, g in tqdm(
        zip(first_df['original'].tolist(), first_df['ground_truth'].tolist()),
        desc='Ref ERRANT', total=len(first_df)
    )
]
ref_dist = edit_type_dist(ref_edits)

print('Reference error-type distribution (top 10):')
for k, v in sorted(ref_dist.items(), key=lambda x: -x[1])[:10]:
    print(f'  {k}: {v:.3f}')

Collecting en-core-web-sm==3.8.0

  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/12.8 MB ? eta -:--:--

     ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/12.8 MB 7.1 MB/s eta 0:00:02

     ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/12.8 MB 8.0 MB/s eta 0:00:02

     ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/12.8 MB 7.2 MB/s eta 0:00:02

     ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 5.2/12.8 MB 6.5 MB/s eta 0:00:02

     ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 6.6/12.8 MB 6.6 MB/s eta 0:00:01

     ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━ 7.9/12.8 MB 6.7 MB/s eta 0:00:01

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 9.7/12.8 MB 6.9 MB/s eta 0:00:01

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 11.5/12.8 MB 7.2 MB/s eta 0:00:01

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 6.9 MB/s  0:00:01

Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

Ref ERRANT:   0%|          | 0/100 [00:00<?, ?it/s]

Ref ERRANT:   5%|▌         | 5/100 [00:00<00:02, 46.04it/s]

Ref ERRANT:  13%|█▎        | 13/100 [00:00<00:01, 64.31it/s]

Ref ERRANT:  20%|██        | 20/100 [00:00<00:01, 62.16it/s]

Ref ERRANT:  27%|██▋       | 27/100 [00:00<00:01, 55.72it/s]

Ref ERRANT:  33%|███▎      | 33/100 [00:00<00:01, 56.88it/s]

Ref ERRANT:  44%|████▍     | 44/100 [00:00<00:00, 71.31it/s]

Ref ERRANT:  54%|█████▍    | 54/100 [00:00<00:00, 77.47it/s]

Ref ERRANT:  62%|██████▏   | 62/100 [00:00<00:00, 72.49it/s]

Ref ERRANT:  70%|███████   | 70/100 [00:01<00:00, 65.55it/s]

Ref ERRANT:  79%|███████▉  | 79/100 [00:01<00:00, 70.60it/s]

Ref ERRANT:  87%|████████▋ | 87/100 [00:01<00:00, 71.67it/s]

Ref ERRANT:  95%|█████████▌| 95/100 [00:01<00:00, 60.64it/s]

Ref ERRANT: 100%|██████████| 100/100 [00:01<00:00, 66.16it/s]

Reference error-type distribution (top 10):
  R:OTHER: 0.199
  R:NOUN: 0.143
  R:SPELL: 0.060
  M:DET: 0.058
  R:ORTH: 0.048
  R:PREP: 0.046
  R:VERB: 0.042
  R:VERB:FORM: 0.035
  R:NOUN:NUM: 0.028
  R:VERB:TENSE: 0.028

In [24]:
errant_results = {}
for variant, df_v in corrected.items():
    hyp_edits = [
        get_edits(g, t)
        for g, t in tqdm(
            zip(df_v['generated'].tolist(), df_v['t5_corrected'].tolist()),
            desc=f'ERRANT {variant}', total=len(df_v)
        )
    ]
    hyp_dist = edit_type_dist(hyp_edits)
    errant_results[variant] = {
        'f0.5':    round(dist_f05(hyp_dist, ref_dist), 3),
        'n_edits': round(np.mean([len(e) for e in hyp_edits]), 2),
    }

# Combined leaderboard
leaderboard = pd.DataFrame({
    v: {
        'f0.5':    errant_results[v]['f0.5'],
        'n_edits': errant_results[v]['n_edits'],
        'cola_B':  cola_results[v]['cola_B'],
        'cola_C':  cola_results[v]['cola_C'],
        'sem_sim': sem_results[v]['mean_sim'],
        'B<A':     cola_results[v]['B<A'],
        'C>B':     cola_results[v]['C>B'],
    }
    for v in errant_results
}).T.sort_values('f0.5', ascending=False)

print('\n=== PROMPT LEADERBOARD (sorted by ERRANT F0.5) ===')
print(leaderboard.to_string())
leaderboard.to_csv('prompt_leaderboard.csv')
print('\nSaved prompt_leaderboard.csv')

ERRANT zero_shot:   0%|          | 0/100 [00:00<?, ?it/s]

ERRANT zero_shot:  12%|█▏        | 12/100 [00:00<00:00, 115.08it/s]

ERRANT zero_shot:  24%|██▍       | 24/100 [00:00<00:00, 97.65it/s]

ERRANT zero_shot:  36%|███▌      | 36/100 [00:00<00:00, 105.62it/s]

ERRANT zero_shot:  51%|█████     | 51/100 [00:00<00:00, 120.99it/s]

ERRANT zero_shot:  64%|██████▍   | 64/100 [00:00<00:00, 112.51it/s]

ERRANT zero_shot:  76%|███████▌  | 76/100 [00:00<00:00, 103.73it/s]

ERRANT zero_shot:  90%|█████████ | 90/100 [00:00<00:00, 112.21it/s]

ERRANT zero_shot: 100%|██████████| 100/100 [00:00<00:00, 106.26it/s]

ERRANT one_shot:   0%|          | 0/100 [00:00<?, ?it/s]

ERRANT one_shot:  13%|█▎        | 13/100 [00:00<00:00, 122.77it/s]

ERRANT one_shot:  26%|██▌       | 26/100 [00:00<00:00, 113.93it/s]

ERRANT one_shot:  39%|███▉      | 39/100 [00:00<00:00, 119.57it/s]

ERRANT one_shot:  53%|█████▎    | 53/100 [00:00<00:00, 126.12it/s]

ERRANT one_shot:  67%|██████▋   | 67/100 [00:00<00:00, 129.58it/s]

ERRANT one_shot:  81%|████████  | 81/100 [00:00<00:00, 129.14it/s]

ERRANT one_shot:  96%|█████████▌| 96/100 [00:00<00:00, 134.82it/s]

ERRANT one_shot: 100%|██████████| 100/100 [00:00<00:00, 128.84it/s]

ERRANT few_shot_3:   0%|          | 0/100 [00:00<?, ?it/s]

ERRANT few_shot_3:  13%|█▎        | 13/100 [00:00<00:00, 123.55it/s]

ERRANT few_shot_3:  27%|██▋       | 27/100 [00:00<00:00, 129.00it/s]

ERRANT few_shot_3:  40%|████      | 40/100 [00:00<00:00, 121.38it/s]

ERRANT few_shot_3:  55%|█████▌    | 55/100 [00:00<00:00, 125.51it/s]

ERRANT few_shot_3:  69%|██████▉   | 69/100 [00:00<00:00, 129.88it/s]

ERRANT few_shot_3:  83%|████████▎ | 83/100 [00:00<00:00, 131.14it/s]

ERRANT few_shot_3:  98%|█████████▊| 98/100 [00:00<00:00, 135.09it/s]

ERRANT few_shot_3: 100%|██████████| 100/100 [00:00<00:00, 131.09it/s]

ERRANT few_shot_12:   0%|          | 0/100 [00:00<?, ?it/s]

ERRANT few_shot_12:  15%|█▌        | 15/100 [00:00<00:00, 149.44it/s]

ERRANT few_shot_12:  31%|███       | 31/100 [00:00<00:00, 153.63it/s]

ERRANT few_shot_12:  47%|████▋     | 47/100 [00:00<00:00, 146.66it/s]

ERRANT few_shot_12:  62%|██████▏   | 62/100 [00:00<00:00, 140.38it/s]

ERRANT few_shot_12:  77%|███████▋  | 77/100 [00:00<00:00, 142.87it/s]

ERRANT few_shot_12:  93%|█████████▎| 93/100 [00:00<00:00, 146.95it/s]

ERRANT few_shot_12: 100%|██████████| 100/100 [00:00<00:00, 146.17it/s]

ERRANT cot:   0%|          | 0/100 [00:00<?, ?it/s]

ERRANT cot:  17%|█▋        | 17/100 [00:00<00:00, 164.78it/s]

ERRANT cot:  34%|███▍      | 34/100 [00:00<00:00, 160.66it/s]

ERRANT cot:  51%|█████     | 51/100 [00:00<00:00, 163.50it/s]

ERRANT cot:  68%|██████▊   | 68/100 [00:00<00:00, 158.71it/s]

ERRANT cot:  84%|████████▍ | 84/100 [00:00<00:00, 156.56it/s]

ERRANT cot: 100%|██████████| 100/100 [00:00<00:00, 155.26it/s]

ERRANT cot: 100%|██████████| 100/100 [00:00<00:00, 157.53it/s]

=== PROMPT LEADERBOARD (sorted by ERRANT F0.5) ===
              f0.5 n_edits cola_B cola_C sem_sim    B<A    C>B
zero_shot    0.689    1.19    0.0    0.0   0.112  False  False
one_shot     0.659    0.97    0.0    0.0   0.094  False  False
few_shot_3   0.639    0.94    0.0    0.0   0.089  False  False
few_shot_12  0.591    0.78    0.0    0.0   0.054  False  False
cot          0.468    0.69    0.0    0.0   0.033  False  False

Saved prompt_leaderboard.csv

## Step 5 — Ablation Study

Change **one variable at a time** vs the `few_shot_12` baseline.
Run on `N_ABL = min(30, len(src))` sentences to conserve API quota.

| Variable | Values tested | Fixed |
|----------|--------------|-------|
| Instruction wording | concise vs detailed | T=0.7, 12-shot |
| Temperature | 0.3 / 0.7 / 1.0 | detailed instr, 12-shot |
| n_examples | 0 / 1 / 3 / 12 | detailed instr, T=0.7 |
| CoT | off / on | detailed instr, T=0.7 |

n_examples 0/1/3/12 and CoT results come from the main run above (sliced to N_ABL).

In [25]:
N_ABL = min(30, len(src))
abl_src = src[:N_ABL]
abl_gt  = gt[:N_ABL]

# ── Instruction wording ──────────────────────────────────────────────────────
INSTR_CONCISE = (
    'Generate a new sentence with the same grammatical error type. '
    'New sentence only, numbered.'
)
INSTR_DETAILED = (
    'You are an expert linguist specializing in grammatical error generation. '
    'Create a completely new, original sentence that exhibits the same category of '
    'grammatical error as the given sentence. Use an entirely different topic. '
    'Preserve the original numbering. Output only the generated sentences.'
)

NEW_ABLATION_CONFIGS = {
    # Instruction wording (12-shot, T=0.7)
    'instr_concise':  make_few_shot_chain(pairs_12, temperature=0.7),  # swap instruction below
    'instr_detailed': make_few_shot_chain(pairs_12, temperature=0.7),
    # Temperature (12-shot, detailed instr, T=0.3 / 1.0 — 0.7 covered by few_shot_12 main)
    'temp_0.3': make_few_shot_chain(pairs_12, temperature=0.3),
    'temp_1.0': make_few_shot_chain(pairs_12, temperature=1.0),
}

# Patch instruction wording into concise / detailed chains
def make_wording_chain(instr, pairs, temperature=0.7):
    block = make_few_shot_block(pairs)
    prompt = ChatPromptTemplate.from_messages([
        ('human', instr + '\n\n' + block + 'Now generate for:\n{batch_input}')
    ])
    return prompt | make_llm(temperature) | StrOutputParser()

NEW_ABLATION_CONFIGS['instr_concise']  = make_wording_chain(INSTR_CONCISE,  pairs_12)
NEW_ABLATION_CONFIGS['instr_detailed'] = make_wording_chain(INSTR_DETAILED, pairs_12)

print(f'Ablation: {len(NEW_ABLATION_CONFIGS)} new configs + main run slices')
print(f'Sentences per config: {N_ABL}')

Ablation: 4 new configs + main run slices
Sentences per config: 30

In [26]:
abl_rows = []

def eval_generated(name, generated, orig_list, gt_list):
    """Score a generated list with T5, CoLA, semantic sim, ERRANT and return a metrics dict."""
    t5_c = correct_sentences(generated)
    a_sc = cola_scores(orig_list)
    b_sc = cola_scores(generated)
    c_sc = cola_scores(t5_c)
    sims = tfidf_sim(orig_list, generated)
    h_edits = [get_edits(g, t) for g, t in zip(generated, t5_c)]
    r_edits = [get_edits(o, g) for o, g in zip(orig_list, gt_list)]
    h_dist  = edit_type_dist(h_edits)
    r_dist  = edit_type_dist(r_edits)
    return {
        'config':  name,
        'f0.5':    round(dist_f05(h_dist, r_dist), 3),
        'cola_B':  round(np.mean(b_sc), 3),
        'cola_C':  round(np.mean(c_sc), 3),
        'sem_sim': round(np.mean(sims),  3),
        'B<A':     bool(np.mean(b_sc) < np.mean(a_sc)),
        'C>B':     bool(np.mean(c_sc) > np.mean(b_sc)),
    }

# Include main-run variants (sliced to N_ABL) for comparison
MAIN_SLICE_VARIANTS = ['zero_shot', 'one_shot', 'few_shot_3', 'few_shot_12', 'cot']
for v in MAIN_SLICE_VARIANTS:
    if v in results:
        abl_rows.append(eval_generated(v, results[v][:N_ABL], abl_src, abl_gt))
        print(f'Evaluated (main slice): {v}')

# Run new ablation configs
for name, chain in NEW_ABLATION_CONFIGS.items():
    print(f'\n--- {name} ---')
    try:
        generated = run_generation(chain, abl_src, batch_size=3, sleep=15, desc=name)
        abl_rows.append(eval_generated(name, generated, abl_src, abl_gt))
        print(f'  f0.5 = {abl_rows[-1]["f0.5"]}')
    except Exception as e:
        print(f'  FAILED: {e}')

abl_df = pd.DataFrame(abl_rows).set_index('config').sort_values('f0.5', ascending=False)
print('\n=== ABLATION LEADERBOARD ===')
print(abl_df.to_string())
abl_df.to_csv('ablation_leaderboard.csv')
print('\nSaved ablation_leaderboard.csv')

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:02<00:06,  2.08s/it]

T5 GEC:  50%|█████     | 2/4 [00:05<00:06,  3.03s/it]

T5 GEC:  75%|███████▌  | 3/4 [00:09<00:03,  3.19s/it]

T5 GEC: 100%|██████████| 4/4 [00:10<00:00,  2.65s/it]

T5 GEC: 100%|██████████| 4/4 [00:10<00:00,  2.75s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:04<00:00,  4.42s/it]

CoLA: 100%|██████████| 1/1 [00:04<00:00,  4.42s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.23s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.23s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.38s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.38s/it]

Evaluated (main slice): zero_shot

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:02<00:06,  2.12s/it]

T5 GEC:  50%|█████     | 2/4 [00:04<00:04,  2.05s/it]

T5 GEC:  75%|███████▌  | 3/4 [00:06<00:02,  2.03s/it]

T5 GEC: 100%|██████████| 4/4 [00:07<00:00,  1.69s/it]

T5 GEC: 100%|██████████| 4/4 [00:07<00:00,  1.82s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.88s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.88s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.41s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.41s/it]

Evaluated (main slice): one_shot

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:01<00:05,  1.73s/it]

T5 GEC:  50%|█████     | 2/4 [00:03<00:03,  1.78s/it]

T5 GEC:  75%|███████▌  | 3/4 [00:05<00:01,  1.71s/it]

T5 GEC: 100%|██████████| 4/4 [00:06<00:00,  1.62s/it]

T5 GEC: 100%|██████████| 4/4 [00:06<00:00,  1.66s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.23s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.16s/it]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.16s/it]

Evaluated (main slice): few_shot_3

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:00<00:02,  1.02it/s]

T5 GEC:  50%|█████     | 2/4 [00:02<00:02,  1.11s/it]

T5 GEC:  75%|███████▌  | 3/4 [00:03<00:01,  1.02s/it]

T5 GEC: 100%|██████████| 4/4 [00:04<00:00,  1.11s/it]

T5 GEC: 100%|██████████| 4/4 [00:04<00:00,  1.08s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.32s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.32s/it]

Evaluated (main slice): few_shot_12

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:00<00:02,  1.03it/s]

T5 GEC:  50%|█████     | 2/4 [00:02<00:02,  1.11s/it]

T5 GEC:  75%|███████▌  | 3/4 [00:04<00:01,  1.87s/it]

T5 GEC: 100%|██████████| 4/4 [00:06<00:00,  1.69s/it]

T5 GEC: 100%|██████████| 4/4 [00:06<00:00,  1.59s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.89s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.89s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]

Evaluated (main slice): cot

--- instr_concise ---

instr_concise:   0%|          | 0/10 [00:00<?, ?it/s]

instr_concise:  10%|█         | 1/10 [03:33<32:00, 213.34s/it]

instr_concise:  20%|██        | 2/10 [04:46<17:26, 130.87s/it]

instr_concise:  30%|███       | 3/10 [08:19<19:37, 168.22s/it]

instr_concise:  40%|████      | 4/10 [11:48<18:26, 184.47s/it]

instr_concise:  50%|█████     | 5/10 [13:23<12:40, 152.14s/it]

instr_concise:  60%|██████    | 6/10 [17:23<12:08, 182.01s/it]

instr_concise:  70%|███████   | 7/10 [18:07<06:50, 136.94s/it]

instr_concise:  80%|████████  | 8/10 [19:42<04:07, 123.64s/it]

instr_concise:  90%|█████████ | 9/10 [20:58<01:48, 108.76s/it]

instr_concise: 100%|██████████| 10/10 [22:47<00:00, 108.87s/it]

instr_concise: 100%|██████████| 10/10 [22:47<00:00, 136.78s/it]

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:00<00:02,  1.02it/s]

T5 GEC:  50%|█████     | 2/4 [00:02<00:02,  1.01s/it]

T5 GEC:  75%|███████▌  | 3/4 [00:02<00:00,  1.03it/s]

T5 GEC: 100%|██████████| 4/4 [00:04<00:00,  1.39s/it]

T5 GEC: 100%|██████████| 4/4 [00:04<00:00,  1.24s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.32s/it]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.32s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.37s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.37s/it]

  f0.5 = 0.551

--- instr_detailed ---

instr_detailed:   0%|          | 0/10 [00:00<?, ?it/s]

instr_detailed:  10%|█         | 1/10 [00:44<06:39, 44.37s/it]

instr_detailed:  20%|██        | 2/10 [01:34<06:22, 47.85s/it]

instr_detailed:  30%|███       | 3/10 [02:26<05:47, 49.67s/it]

instr_detailed:  40%|████      | 4/10 [03:54<06:29, 64.90s/it]

instr_detailed:  50%|█████     | 5/10 [05:23<06:07, 73.50s/it]

instr_detailed:  60%|██████    | 6/10 [09:47<09:13, 138.43s/it]

instr_detailed:  70%|███████   | 7/10 [10:37<05:27, 109.27s/it]

instr_detailed:  80%|████████  | 8/10 [12:38<03:46, 113.02s/it]

instr_detailed:  90%|█████████ | 9/10 [14:08<01:45, 105.82s/it]

instr_detailed: 100%|██████████| 10/10 [14:49<00:00, 86.04s/it]

instr_detailed: 100%|██████████| 10/10 [14:49<00:00, 89.00s/it]

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:01<00:05,  1.94s/it]

T5 GEC:  50%|█████     | 2/4 [00:03<00:02,  1.47s/it]

T5 GEC:  75%|███████▌  | 3/4 [00:05<00:01,  1.71s/it]

T5 GEC: 100%|██████████| 4/4 [00:06<00:00,  1.55s/it]

T5 GEC: 100%|██████████| 4/4 [00:06<00:00,  1.59s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.88s/it]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.88s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.32s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.32s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]

  f0.5 = 0.501

--- temp_0.3 ---

temp_0.3:   0%|          | 0/10 [00:00<?, ?it/s]

temp_0.3:  10%|█         | 1/10 [12:16<1:50:32, 736.92s/it]

temp_0.3:  20%|██        | 2/10 [13:27<46:00, 345.08s/it]

temp_0.3:  30%|███       | 3/10 [14:17<24:32, 210.39s/it]

temp_0.3:  40%|████      | 4/10 [15:38<15:54, 159.02s/it]

temp_0.3:  50%|█████     | 5/10 [16:21<09:47, 117.46s/it]

temp_0.3:  60%|██████    | 6/10 [17:41<06:58, 104.65s/it]

temp_0.3:  70%|███████   | 7/10 [18:38<04:26, 88.87s/it]

temp_0.3:  80%|████████  | 8/10 [19:29<02:34, 77.00s/it]

temp_0.3:  90%|█████████ | 9/10 [21:02<01:22, 82.04s/it]

temp_0.3: 100%|██████████| 10/10 [21:45<00:00, 69.89s/it]

temp_0.3: 100%|██████████| 10/10 [21:45<00:00, 130.54s/it]

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:00<00:02,  1.10it/s]

T5 GEC:  50%|█████     | 2/4 [00:01<00:01,  1.07it/s]

T5 GEC:  75%|███████▌  | 3/4 [00:03<00:01,  1.35s/it]

T5 GEC: 100%|██████████| 4/4 [00:04<00:00,  1.27s/it]

T5 GEC: 100%|██████████| 4/4 [00:04<00:00,  1.22s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.49s/it]

CoLA: 100%|██████████| 1/1 [00:02<00:00,  2.49s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.34s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.34s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.20s/it]

  f0.5 = 0.455

--- temp_1.0 ---

temp_1.0:   0%|          | 0/10 [00:00<?, ?it/s]

temp_1.0:  10%|█         | 1/10 [01:20<12:01, 80.15s/it]

temp_1.0:  20%|██        | 2/10 [02:32<10:03, 75.40s/it]

temp_1.0:  30%|███       | 3/10 [08:09<22:45, 195.03s/it]

temp_1.0:  40%|████      | 4/10 [09:06<14:02, 140.50s/it]

temp_1.0:  50%|█████     | 5/10 [10:03<09:11, 110.24s/it]

temp_1.0:  60%|██████    | 6/10 [12:15<07:51, 117.90s/it]

temp_1.0:  70%|███████   | 7/10 [12:55<04:36, 92.28s/it]

temp_1.0:  80%|████████  | 8/10 [13:23<02:23, 71.85s/it]

temp_1.0:  90%|█████████ | 9/10 [15:17<01:25, 85.03s/it]

temp_1.0: 100%|██████████| 10/10 [16:00<00:00, 71.91s/it]

temp_1.0: 100%|██████████| 10/10 [16:00<00:00, 96.01s/it]

T5 GEC:   0%|          | 0/4 [00:00<?, ?it/s]

T5 GEC:  25%|██▌       | 1/4 [00:00<00:02,  1.18it/s]

T5 GEC:  50%|█████     | 2/4 [00:02<00:02,  1.40s/it]

T5 GEC:  75%|███████▌  | 3/4 [00:04<00:01,  1.50s/it]

T5 GEC: 100%|██████████| 4/4 [00:05<00:00,  1.42s/it]

T5 GEC: 100%|██████████| 4/4 [00:05<00:00,  1.39s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.76s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.76s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]

CoLA:   0%|          | 0/1 [00:00<?, ?it/s]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]

CoLA: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]

  f0.5 = 0.483

=== ABLATION LEADERBOARD ===
                 f0.5  cola_B  cola_C  sem_sim    B<A    C>B
config
zero_shot       0.598     0.0     0.0    0.097  False  False
instr_concise   0.551     0.0     0.0    0.071  False  False
instr_detailed  0.501     0.0     0.0    0.089  False  False
few_shot_12     0.499     0.0     0.0    0.052  False  False
temp_1.0        0.483     0.0     0.0    0.080  False  False
one_shot        0.475     0.0     0.0    0.097  False  False
few_shot_3      0.466     0.0     0.0    0.074  False  False
temp_0.3        0.455     0.0     0.0    0.087  False  False
cot             0.391     0.0     0.0    0.044  False  False

Saved ablation_leaderboard.csv